# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-09 13:20
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_auto_20160728_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlinksrelatedlink',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_links', to='utils.FooterLinks'),
        ),
    ]
